import { Request, Response } from "express";
import { supabase } from "../supabaseClient";
import { EncryptedNote } from "../../../shared_types/note_types";

export async function getAllNoteNames(req: Request, res: Response) {
    const { userID } = req.body; 

    // Assuming the user ID is supplied in the request body
    if (!userID) {
        return res.status(400).json({ error: "User ID is required" });
    }

    const { data: notes, error } = await supabase
        .from('notes')
        .select('id, note_title, pinned, created_at, updated_at, user_id')
        .eq('user_id', userID)
        .order('created_at', { ascending: false });

    if (error) {
        return res.status(400).json({ error: error.message });
    }

    if (!notes) {
        return res.status(404).json({ error: "No notes found" });
    }

    // Map to partial EncryptedNote structure for listing
    const mappedNotes = notes.map(n => ({
        noteID: n.id,
        encryptedName: n.note_title,
        pinned: n.pinned,
        lastModified: n.updated_at,
        createdAt: n.created_at,
        userID: n.user_id
    }));

    return res.status(200).json({ notes: mappedNotes });
}

export async function getNote(req: Request, res: Response) {

    // Expecting noteID and userID. Note Name is not unique if encrypted without salt per note, 
    // but here we use ID if possible. The original code used noteName.
    const { noteName, userID, noteID } = req.body;

    if (!userID || (!noteName && !noteID)) {
         return res.status(400).json({ error: "UserID and either noteName or noteID are required" });
    }

    let query = supabase.from('notes').select('*').eq('user_id', userID);
    
    if (noteID) {
        query = query.eq('id', noteID);
    } else if (noteName) {
        query = query.eq('note_title', noteName);
    }

    const { data: notes, error: noteError } = await query
                           .order('updated_at', { ascending: false }); // get latest version if duplicates exist
           
    // generic error
    if (noteError) {
        return res.status(400).json({ error: noteError.message });
    }
    
    // note to get not found
    if (!notes || notes.length === 0) {
        return res.status(404).json({ error: "Note not found" });
    }

    const n = notes[0];
    const encryptedNote: EncryptedNote = {
        userID: n.user_id,
        noteID: n.id,
        encryptedName: n.note_title,
        ciphertextB64: n.note_text,
        pinned: n.pinned,
        lastModified: n.updated_at,
        createdAt: n.created_at
    };

    // otherwise note found successfully
    return res.status(200).json({ note: encryptedNote });		
				
}

export async function uploadNote(req: Request, res: Response) {

    const note: EncryptedNote = req.body;

    // Check if required fields are present
    if (!note.encryptedName || !note.ciphertextB64 || !note.userID) {
        return res.status(400).json({ error: "Missing required fields" });
    }

    const { data, error } = await supabase
        .from('notes')
        .insert([{
            id: note.noteID, // Optional, can be auto-generated by DB if omitted, but EncryptedNote has it. 
                             // Ideally we generate ID on client or server. If client sends it, use it.
            note_title: note.encryptedName,
            note_text: note.ciphertextB64,
            pinned: note.pinned,
            user_id: note.userID,
            created_at: note.createdAt || new Date().toISOString(),
            updated_at: note.lastModified || new Date().toISOString()
        }]);

    if (error) {
        const code = (error as any).code;
        // 23505 is Postgres "unique_violation" – treat concurrent duplicate inserts as idempotent
        if (code === "23505") {
            return res.status(200).json({ ok: true, duplicated: true });
        }
        return res.status(400).json({ error: error.message });
    }

    // otherwise note uploaded successfully
     return res.status(201).json({ ok: true });
    
}

// handles any update to the note 
export async function updateNote(req: Request, res: Response) {

    const note: EncryptedNote = req.body;

    const { data, error } = await supabase
        .from('notes')
        .update({
            note_title: note.encryptedName,
            note_text: note.ciphertextB64,
            pinned: note.pinned,
            updated_at: note.lastModified || new Date().toISOString()
        })
        .eq('id', note.noteID)
        .eq('user_id', note.userID);

    if (error) {
        return res.status(400).json({ error: error.message });
    }

    return res.status(200).json({ ok: true });

}

export async function deleteNote(req: Request, res: Response) {

    const { noteID, userID } = req.body; // Expecting noteID and userID

    if (!userID || !noteID) {
        return res.status(400).json({ error: "userID and noteID are required" });
    }
	
	const { data, error } = await supabase
	.from('notes')
	.delete()
	.eq('id', noteID)
    .eq('user_id', userID); 

    // generic error
    if (error) {
        return res.status(400).json({ error: error.message });
    }

    // otherwise note deleted successfully
	return res.status(200).json({ ok: true });
    
}